# Numpy: Numerical Python, 主要可進行陣列(Array)運算，執行速度比串列快

In [ ]:
# Numpy array稱為ndarray

# 安裝
# 可直接使用Anaconda Navigator進行安裝
# 底下內容參考https://www.w3schools.com/

In [ ]:
#--------------------------------------------------------------------------------
# 簡介
#--------------------------------------------------------------------------------
# 匯入(Import)
import numpy # numpy所提供功能可使用

# 宣告numpy陣列arr，並指定內容
arr = numpy.array([1, 2, 3, 4, 5]) # 注意()內使用[]存放資料

# 顯示陣列
print(arr)

[1 2 3 4 5]


In [ ]:
# 宣告別名(Alias)
import numpy as np # 表示後續可使用np代表numpy

# 宣告numpy陣列arr，並指定內容
arr = np.array([1, 2, 3, 4, 5]) # 注意此處使用np而非numpy

# 顯示陣列
print(arr)

[1 2 3 4 5]


In [ ]:
# 檢查numpy版本
import numpy as np

print(np.__version__) # version前後各兩個底線

1.19.1


In [ ]:
#--------------------------------------------------------------------------------
#%%
# 產生numpy array: 使用array函數
import numpy as np

# 宣告numpy的ndarray物件，並指定內容
arr = np.array([1, 2, 3, 4, 5])

# 顯示陣列內容
print(arr)

# 顯示陣列類型
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#--------------------------------------------------------------------------------
#%%
# 可將串列(list)、元組(tuple)或類陣列資料結構轉為ndarray

In [ ]:
#--------------------------------------------------------------------------------
#%%
# 陣列的維度(Dimensions)
# 0維陣列(或稱Scalars)：也就是陣列中的元素(Element)
import numpy as np

# 宣告0維陣列，值為42
arr = np.array(42)

# 顯示陣列內容
print(arr)

# 顯示陣列類型
print(type(arr))

42
<class 'numpy.ndarray'>


In [ ]:
#--------------------------------------------------------------------------------
#%%
# 1維陣列

# 產生numpy array: 使用array函數
import numpy as np

# 宣告numpy的ndarray物件，並指定內容
arr = np.array([1, 2, 3, 4, 5])

# 顯示陣列內容
print(arr)

# 顯示陣列類型
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#--------------------------------------------------------------------------------
#%%
# 2維陣列(可直接看右側]數量判斷)
import numpy as np

# 宣告陣列，內含兩個1維陣列
arr = np.array([[1, 2, 3], [4, 5, 6]])

# 顯示陣列內容
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
#--------------------------------------------------------------------------------
#%%
# 3維陣列

import numpy as np

# 內含兩個2維陣列，2維陣列各包含2個1維陣列，3個元素
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

# 顯示陣列內容
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
#--------------------------------------------------------------------------------
#%%
# 檢查陣列維度: 使用ndim功能
import numpy as np

# 0維陣列
a = np.array(42)

# 1維陣列
b = np.array([1, 2, 3, 4, 5])

# 2維陣列
c = np.array([[1, 2, 3], [4, 5, 6]])

# 3維陣列: 可判斷最右邊]個數來計算維度
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

# 顯示維度
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
#--------------------------------------------------------------------------------
#%%
# 高維度陣列
import numpy as np

# 使用ndim參數設定維度
arr = np.array([1, 2, 3, 4], ndmin = 5)

# 顯示陣列內容
print(arr)

# 請計算最右邊]個數
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


## 產生特殊陣列

In [ ]:
#--------------------------------------------------------------------------------
#%% 產生特殊陣列
import numpy as np

arr_zeros = np.zeros(10, dtype = int) #建立一個內容為0 長度為10的整數陣列

arr_ones = np.ones((3,5) ,dtype=float)  #建立一個內容為1 3x5 的浮點數陣列

arr_empty = np.empty((3,2) )  #建立一個內容為1 3x2 的無初始值陣列

# 顯示結果
print(arr_zeros)
print(arr_ones)
print(arr_empty)


[0 0 0 0 0 0 0 0 0 0]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[4.24399158e-314 8.48798317e-314]
 [1.27319747e-313 1.69759663e-313]
 [2.12199579e-313 2.54639495e-313]]


In [ ]:
#--------------------------------------------------------------------------------
#%% 產生特殊陣列：等差數列
import numpy as np

arr_arange = np.arange(0, 20, 2) #建立一個依序填滿的陣列 0到20間隔為2
arr_linspace = np.linspace(0, 1, 5) #建立一個5個值的陣列，在0到1間平均分布為5個數字

# 顯示結果
print('arr_arange---->', arr_arange)
print('arr_linspace---->', arr_linspace)

arr_arange----> [ 0  2  4  6  8 10 12 14 16 18]
arr_linspace----> [0.   0.25 0.5  0.75 1.  ]


# Numpy陣列索引(Indexing)

In [ ]:
#--------------------------------------------------------------------------------
#%%
#--------------------------------------------------------------------------------
# Numpy陣列索引(Indexing)
#--------------------------------------------------------------------------------
# 索引由0開始，0代表第1個元素
import numpy as np

arr = np.array([1, 2, 3, 4])

# 第1個元素
print(arr[0])

# 請自行嘗試取得其他元素

1


In [ ]:
#--------------------------------------------------------------------------------
#%%
import numpy as np

# 宣告1維陣列
arr = np.array([1, 2, 3, 4])

# 將第3和4元素相加
print(arr[2] + arr[3])

7


In [ ]:
#--------------------------------------------------------------------------------
#%%
# 存取2維陣列: 以逗號分隔[維度,元素]方式
import numpy as np

# 宣告2維陣列
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

# 第1維度，第2元素(維度與元素皆從0開始)
print('2nd element on 1st dim: ', arr[0, 1])

2nd element on 1st dim:  2


In [ ]:
#--------------------------------------------------------------------------------
#%%
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

# 請先思考底下指令結果？
print('5th element on 2nd dim: ', arr[1, 4])

5th element on 2nd dim:  10


In [ ]:
#--------------------------------------------------------------------------------
#%%
# 3維陣列

import numpy as np

# 宣告3維陣列
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# 取得第1個陣列(0)中的第2個陣列(1)的第3個(2)元素
print(arr[0, 1, 2])

#--------------------------------------------------------------------------------
# 執行步驟說明

# The first number represents the first dimension, which contains two arrays:
# [[1, 2, 3], [4, 5, 6]]
# and:
# [[7, 8, 9], [10, 11, 12]]
# Since we selected 0, we are left with the first array:
# [[1, 2, 3], [4, 5, 6]]

# The second number represents the second dimension, which also contains two arrays:
# [1, 2, 3]
# and:
# [4, 5, 6]
# Since we selected 1, we are left with the second array:
# [4, 5, 6]

# The third number represents the third dimension, which contains three values:
# 4
# 5
# 6
# Since we selected 2, we end up with the third value:
# 6
#--------------------------------------------------------------------------------

6


In [ ]:
#--------------------------------------------------------------------------------
#%%

# 負索引(Negative indexing)
import numpy as np

# 宣告2維陣列
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

# -1表最後一個元素，1表弟2個陣列
print('Last element from 2nd dim: ', arr[1, -1])

# 陣列切割(Slicing)

In [ ]:
#--------------------------------------------------------------------------------
#%%
#--------------------------------------------------------------------------------
# 陣列切割(Slicing): 切割表示從兩個索引間取出資料
# 一般語法： [起，迄，間隔]，起未指定表從0開始，間隔未指定則以1代表，迄未指定則到最後1筆資料
#--------------------------------------------------------------------------------

import numpy as np

# 宣告1維陣列
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# 起1，迄5，表第2-第4個元素
print(arr[1:5])

[2 3 4 5]


In [ ]:
#--------------------------------------------------------------------------------
#%%: 未指定[迄]

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# 未指定迄，則取到最後一筆資料
print(arr[4:])

[5 6 7]


In [ ]:
#--------------------------------------------------------------------------------
#%%: 未指定[起]

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# 從第1筆到第3筆，不含第4筆
print(arr[:4])

[1 2 3 4]


In [ ]:
#--------------------------------------------------------------------------------
#%%: 負切割(Negative slicing)

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# -1表最後1個，-3表最後第3個，但-1是[迄]，不包括
print(arr[-3:-1])

[5 6]


In [ ]:
#--------------------------------------------------------------------------------
#%%: 間隔

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# 間隔2，索引範圍：1,3,5，但5不包括
print(arr[1:5:2])

[2 4]


In [ ]:
#--------------------------------------------------------------------------------
#%%: 僅間隔，未指定起迄

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# 間隔2的所有元素: 1,3,5,7
print(arr[::2])

[1 3 5 7]


In [ ]:
#--------------------------------------------------------------------------------
#%%: 切割2維陣列

import numpy as np

# 宣告2維陣列
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# 第2維度，第1-3個元素,4不含
print(arr[1, 1:4])

[7 8 9]


In [ ]:
#--------------------------------------------------------------------------------
#%%

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# 2個陣列的第2個元素，未指定起迄，數字直接代表元素位置
print(arr[0:2, 2])

[3 8]


In [ ]:
#--------------------------------------------------------------------------------
#%%

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# 指定起迄，迄均不包含
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


# Numpy資料類型

In [ ]:
#--------------------------------------------------------------------------------
#%%: Numpy資料類型
#--------------------------------------------------------------------------------
# Python資料類型(僅列舉主要)
## string: 字元
## integer: 整數
## float: 浮點數(含小數位數)
## boolean: 布林值

# Numpy資料類型(僅列舉主要)
## i: integer
## b: boolean
## u: unsigned integer (正數)
## f: float
## M: datetime
## S: string
## U: unicode string

In [ ]:
#--------------------------------------------------------------------------------
#%% 確認array資料類型
import numpy as np

arr = np.array([1, 2, 3, 4])

# 使用.dtype
print(arr.dtype)

int32


In [ ]:
#--------------------------------------------------------------------------------
#%%

import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

# 顯示陣列資料類型: Python3使用Unicode方式表達字串
print(arr.dtype)

<U6


In [ ]:
#--------------------------------------------------------------------------------
#%%: 產生陣列時指定資料型態

import numpy as np

arr = np.array([1, 2, 3, 4], dtype = 'S') # 字串類型

print(arr)

# 顯示陣列資料類型: b表示byte-string
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
#--------------------------------------------------------------------------------
#%%: 產生陣列時指定資料型態及大小

import numpy as np

arr = np.array([1, 2, 3, 4], dtype = 'i4') # i4為4bytes (8*4個01組合)的integer

print(arr)

# 顯示資料類型
print(arr.dtype)

[1 2 3 4]
int32


In [ ]:
#--------------------------------------------------------------------------------
#%%: 資料類型轉換有問題

import numpy as np

arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

In [ ]:
#--------------------------------------------------------------------------------
#%%: 資料類型轉換-方法一

import numpy as np

arr = np.array([1.1, 2.1, 3.1])

# 轉換為整數
newarr = arr.astype('i')

# 顯示結果
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [ ]:
#--------------------------------------------------------------------------------
#%%: 資料類型轉換-方法二

import numpy as np

arr = np.array([1.1, 2.1, 3.1])

# 指定int
newarr = arr.astype(int)

# 顯示結果
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [ ]:
#--------------------------------------------------------------------------------
#%%: 資料類型轉換--整數-->布林值

import numpy as np

arr = np.array([1, 0, 3])

# 指定bool
newarr = arr.astype(bool)

# 顯示結果
print(newarr) # 非0就是True
print(newarr.dtype)

[ True False  True]
bool


# Copy vs. View

In [ ]:
#--------------------------------------------------------------------------------
#%%: Copy vs View: https://www.w3schools.com/python/numpy_copy_vs_view.asp
# Copy為新陣列
# View為原陣列
#--------------------------------------------------------------------------------
import numpy as np

# 宣告一維陣列
arr = np.array([1, 2, 3, 4, 5])

# 將arr複製(Copy)一份
x = arr.copy()

# 修改arr的第1格元素
arr[0] = 42

# 顯示arr
print(arr)

# 顯示複製的陣列
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
#--------------------------------------------------------------------------------
#%%: 
import numpy as np

# 宣告陣列
arr = np.array([1, 2, 3, 4, 5])

# 使用view，可想成是Windows中的捷徑
x = arr.view()

# 修改arr的第1個元素，x內容跟著被改
arr[0] = 42

# 顯示arr: 被更改
print(arr)

# 顯示x: 被更改
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
#--------------------------------------------------------------------------------
#%%: 修改view

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()

# 修改第1個元素
x[0] = 31

# 顯示arr: 被更改
print(arr)

# 顯示x: 被更改
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [ ]:
#--------------------------------------------------------------------------------
#%%: 檢查變數是否有自己的資料
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# x使用copy，表與arr不同資料
x = arr.copy()

# y使用view, 表與arr相同資料
y = arr.view()

# 如顯示None，表示自己擁有自己的資料
print(x.base)
print(y.base)

None
[1 2 3 4 5]


# 陣列形狀(Array shape)

In [ ]:
#@title
# https://www.w3schools.com/python/numpy_array_shape.asp

In [ ]:
#@title
#--------------------------------------------------------------------------------
#%%:
import numpy as np

# 二維陣列: 每個陣列有4個元素
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# 顯示形狀
print(arr.shape)


(2, 4)


In [ ]:
#@title
#--------------------------------------------------------------------------------
#%%: 
import numpy as np

# 宣告5維陣列
arr = np.array([1, 2, 3, 4], ndmin = 5)

# 顯示陣列內容
print(arr)

# 顯示陣列形狀
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


# 陣列變型(Array reshape)

In [ ]:
#--------------------------------------------------------------------------------
#%%: 1維->2維

import numpy as np

# 1維陣列
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# 轉為2維，4個陣列，每個陣列3個元素
newarr = arr.reshape(4, 3)

# 顯示陣列內容
print(arr)
print(newarr)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#--------------------------------------------------------------------------------
#%%: 1維->3維

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# 變成2個陣列，各含3個陣列(內含2個元素)
newarr = arr.reshape(2, 3, 2)

# 顯示陣列內容
print(arr)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
#--------------------------------------------------------------------------------
#%%: 形狀不同陣列無法互轉

import numpy as np

# 1*8 = 8
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# 3*3 = 9
newarr = arr.reshape(3, 3)

print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

In [ ]:
#--------------------------------------------------------------------------------
#%%: 轉成一維陣列: flattend or ravel
import numpy as np

arr = np.array([[4, 5, 6], [1, 2, 3]])

# -1表扁平化陣列，變成一維
newarr = arr.reshape(-1)

print(newarr)

[4 5 6 1 2 3]


In [ ]:
#--------------------------------------------------------------------------------
#%%: 轉成一維陣列: flattend or ravel
import numpy as np

arr = np.array([[4, 5, 6], [1, 2, 3]])

# -1表扁平化陣列，變成一維
newarr = arr.ravel()

print(newarr)

[4 5 6 1 2 3]


# 陣列繞圈(Iterating)

In [ ]:
#--------------------------------------------------------------------------------
#%%: 一維陣列

import numpy as np

# 宣告陣列
arr = np.array([1, 2, 3])

# 利用for迴圈
for x in arr:
  
  # 顯示陣列元素  
  print(x)

1
2
3


In [ ]:
#--------------------------------------------------------------------------------
#%%: 二維陣列: 依據每個維度內容依序，仍回傳陣列

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  
  # 顯示陣列元素
  print(x)

[1 2 3]
[4 5 6]


In [ ]:
#--------------------------------------------------------------------------------
#%%: 多維陣列回傳實際值，非以陣列形式回傳

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

# 第一層迴圈：維度
for x in arr:
  
  # 第二層迴圈：陣列內元素
  for y in x:
    
    # 顯示陣列內實際值
    print(y)

1
2
3
4
5
6


In [ ]:
#--------------------------------------------------------------------------------
#%%: 三維陣列: 依據每個維度內容依序，仍回傳陣列

import numpy as np

# 宣告三維陣列
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    
    # 顯示陣列元素 
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [ ]:
#--------------------------------------------------------------------------------
#%%: 修改view

import numpy as np

# 宣告三維陣列
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])


# 第一層迴圈
for x in arr:
    
    # 第二層迴圈
    for y in x:
        
        # 第三層迴圈
        for z in y:
            
            # 顯示陣列內容  
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
#--------------------------------------------------------------------------------
#%%: nditer功能：解決多維度陣列回傳陣列問題

import numpy as np

# 宣告三維陣列
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# 顯示arr

# 直接以nditer顯示陣列內元素
for x in np.nditer(arr):
  print(x)


1
2
3
4
5
6
7
8


In [ ]:
#--------------------------------------------------------------------------------
#%%: 陣列繞圈時修改資料類型態(進階)

import numpy as np

arr = np.array([1, 2, 3])

# buffered為資料暫存，供python轉換資料
for x in np.nditer(arr, flags = ['buffered'], op_dtypes = ['S']):
  print(x)



b'1'
b'2'
b'3'


In [ ]:
#--------------------------------------------------------------------------------
#%%: 陣列繞圈時指定間隔

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# 每個維度，每個陣列，索引間隔2方式繞圈
for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [ ]:
#--------------------------------------------------------------------------------
#%%: ndenumerate: 可回傳資料的順序編號

import numpy as np

arr = np.array([1, 2, 3])

# idx維順序編號，x為陣列內元素
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [ ]:
#--------------------------------------------------------------------------------
#%%: ndenumerate: 可回傳資料的順序編號，二維陣列

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# idx同樣為陣列順序編號
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


# 陣列合併(Join)

In [ ]:
# https://www.w3schools.com/python/numpy_array_join.asp
# concatenate()：合併/串接
# vstack()：垂直合併/串接
# hstack()：水平合併/串接

In [ ]:
#--------------------------------------------------------------------------------
#%%: 三個功能預覽

import numpy as np

# 產生1維陣列
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# 顯示結果
print('concatenate----->', np.concatenate([x, y]))    # 串接陣列
print('vstack----->', np.vstack([x, y]))              # 垂直串接
print('hstack----->', np.hstack([x, y]))              # 水平串接

concatenate-----> [1 2 3 4 5 6]
vstack-----> [[1 2 3]
 [4 5 6]]
hstack-----> [1 2 3 4 5 6]


In [ ]:
#--------------------------------------------------------------------------------
#%%: concatenate：合併兩個一維陣列

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

# 實際合併陣列
arr = np.concatenate((arr1, arr2))

# 顯示合併後陣列
print(arr)

[1 2 3 4 5 6]


In [ ]:
#--------------------------------------------------------------------------------
#%%: concatenate：合併兩個二維陣列

import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

# 顯示原始陣列
print(arr1)
print(arr2)

# [
# [1 2] [3 4]
# 
# ]
# [
# [5 6] [7 8]
# 
# ]

# 實際合併陣列，可參考：https://www.twblogs.net/a/5c0e6f7cbd9eee5e40bacb1b
# https://blog.csdn.net/lbj23hao1/article/details/103695077
arr = np.concatenate((arr1, arr2), axis = 1) # axis = 1指依欄(Column，由上而下)合併，預設為列(axis = 0)

# 顯示合併後陣列
print(arr)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#--------------------------------------------------------------------------------
#%%: stack功能，與concatenate類似，但產生新維度

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

# 顯示原始陣列
print(arr1)
print(arr2)

# [
# [1 2 3]
# 
# ]
# [
# [4 5 6]
# 
# ]


# 實際合併陣列
arr = np.stack((arr1, arr2), axis = 1) # axis = 1指依欄(Column，由上而下)合併

# 顯示合併後陣列，注意多了一組[]
print(arr)

[1 2 3]
[4 5 6]
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
#--------------------------------------------------------------------------------
#%%: hstack功能: 依據列(Row)合併陣列，與concatenate類似，不產生新維度

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

# 水平合併
arr = np.hstack((arr1, arr2))

# 顯示合併後陣列
print(arr)

[1 2 3 4 5 6]


In [ ]:
#--------------------------------------------------------------------------------
#%%: vstack功能: 依據欄(Column)合併陣列，與concatenate類似，但產生新維度

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

# 垂直合併
arr = np.vstack((arr1, arr2))

# 顯示合併後陣列
print(arr)

[[1 2 3]
 [4 5 6]]


# 陣列切割(Split)

In [ ]:
# https://www.w3schools.com/python/numpy_array_split.asp

In [ ]:
#--------------------------------------------------------------------------------
#%%: array_split(array,index, axis = 0)函數：array表陣列，index表切割數量，axis表依列(0，預設)或欄(1)切割

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

# 切割成3個陣列
newarr = np.array_split(arr, 3)

# 顯示切割後陣列
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
#--------------------------------------------------------------------------------
#%%: 萬一陣列元素無法均分時，從後面調整

import numpy as np

# 6個元素
arr = np.array([1, 2, 3, 4, 5, 6])

# 切成4個陣列
newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [ ]:
#--------------------------------------------------------------------------------
#%%: array_split仍回傳陣列，存取方式與陣列元素存取方式相同

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [ ]:
#--------------------------------------------------------------------------------
#%%: 2維陣列切割->2維陣列

import numpy as np

# 宣告2維陣列，陣列中包含6個陣列
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

# 切割成3個陣列
newarr = np.array_split(arr, 3)

# 顯示切割後結果
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [ ]:
#--------------------------------------------------------------------------------
#%%: 2維陣列切割->2維陣列

import numpy as np

# 宣告2維陣列，陣列中包含6個陣列，每個子陣列包含3個元素
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

# 
newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [ ]:
#--------------------------------------------------------------------------------
#%%: 依欄(Column)切割陣列

import numpy as np

# 宣告2維陣列
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

# 切割成3個陣列
newarr = np.array_split(arr, 3, axis = 1) # 依欄切割(由上而下)

# [[1,   2,  3]
#  [4,   5,  6]
#  [7,   8,  9]
#  [10, 11, 12]
#  [13, 14, 15]
#  [16, 17, 18]
# ]


# 顯示結果
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
#--------------------------------------------------------------------------------
#%%: 依列(Row)切割陣列

import numpy as np

# 宣告2維陣列
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

# 切割成3個陣列
newarr = np.array_split(arr, 3, axis = 0) # 依列切割(由左而右)

# [[1,   2,  3]
#  [4,   5,  6]
#  [7,   8,  9]
#  [10, 11, 12]
#  [13, 14, 15]
#  [16, 17, 18]
# ]

# 顯示結果
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [ ]:
#--------------------------------------------------------------------------------
#%%: hsplit: 水平切割

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

# [1, 2, 3]
# [4, 5, 6]
# [7, 8, 9]
# [10, 11, 12]
# [13, 14, 15]
# [16, 17, 18]


newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
#--------------------------------------------------------------------------------
#%%: vsplit: 垂直切割

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.vsplit(arr, 3)

print(newarr)


[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


# 陣列搜尋(Search)

In [ ]:
# https://www.w3schools.com/python/numpy_array_split.asp

In [ ]:
#--------------------------------------------------------------------------------
#%%: where指令: 參數為特定值，找到則回傳值的索引(index)，未找到則回傳空值

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

# 找到值為4的索引
x = np.where(arr == 4)

# 顯示索引
print(x)


(array([], dtype=int64),)


In [ ]:
#--------------------------------------------------------------------------------
#%%: 找到值為偶數的索引

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr % 2 == 0)

# 顯示結果
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [ ]:
#--------------------------------------------------------------------------------
#%%: 找到值為奇數的索引

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr % 2 == 1)

# 顯示結果
print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [ ]:
#--------------------------------------------------------------------------------
#%%: searchsorted: 僅限已排序的陣列，目的是維持陣列排序內容，新的值該加在何處

import numpy as np

arr = np.array([6, 7, 8, 9])

# 7該加在何位置
x = np.searchsorted(arr, 7)

# 顯示
print(x)

# 請試試10該放的位置？才能維持原本順序

4


In [ ]:
#--------------------------------------------------------------------------------
#%%: searchsorted預設從左往右搜尋，可透過side參數改成由右往左

import numpy as np

arr = np.array([6, 7, 8, 9])

# 加入side = 'right'參數，改變搜尋方向
x = np.searchsorted(arr, 7, side = 'right')

# 顯示結果
print(x)


2


In [ ]:
#--------------------------------------------------------------------------------
#%%: 搜尋多個值

import numpy as np

arr = np.array([1, 3, 5, 7])

# 注意需使用[]符號
x = np.searchsorted(arr, [2, 4, 6])

# 顯示結果
print(x)

[1 2 3]


# 陣列排序(Sort)

In [ ]:
# https://www.w3schools.com/python/numpy_array_sort.asp

In [ ]:
#--------------------------------------------------------------------------------
#%%: sort函數：排序數字

import numpy as np

arr = np.array([3, 2, 0, 1])

# 依數值方式遞增排序
print(np.sort(arr))


[0 1 2 3]


In [ ]:
#--------------------------------------------------------------------------------
#%%: sort函數：排序文字

import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

# 依文字從小到大排序
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [ ]:
#--------------------------------------------------------------------------------
#%%: 排序布林值

import numpy as np

# 非0是True，0為False
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [ ]:
#--------------------------------------------------------------------------------
#%%: 排序2維陣列

import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

# 兩個陣列依序排序
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


# 陣列篩選(Filter)

In [ ]:
# https://www.w3schools.com/python/numpy_array_filter.asp

In [ ]:
#--------------------------------------------------------------------------------
#%%: 過濾(Filter)：從陣列中找出符合條件的資料，再產生新陣列

import numpy as np

arr = np.array([41, 42, 43, 44])

# 利用True/False方式表達是否保留陣列資料(True是保留)，同時True/False位置也對應陣列索引
# []表示利用串列結構儲存True/False
x = [True, False, True, False] # 保留第0/2個元素

# 產生新陣列
newarr = arr[x]

# 顯示結果
print(newarr)


[41 43]


In [ ]:
#--------------------------------------------------------------------------------
#%%: 利用過濾條件方式決定是否將陣列元素留下

import numpy as np

# 宣告陣列
arr = np.array([41, 42, 43, 44])

# 產生一個空排串列(List)
filter_arr = []

# 利用for迴圈，把陣列每一個元素繞過一圈
for element in arr:
  
  # 如元素的值大於42才保留 
  if element > 42:

    filter_arr.append(True) # 利用append函數將True加到串列
  
  else: # 否則移除
    
    filter_arr.append(False) # 利用append函數將False加到串列

# 顯示filter_arr內容
print(filter_arr)

# 利用True/False與位置方式決定是否將arr的元素取出並存放於newarr陣列
newarr = arr[filter_arr]

# 顯示新陣列
print(newarr)

[False, False, True, True]
[43 44]


In [ ]:
#--------------------------------------------------------------------------------
#%%: 過濾偶數元素才留下

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# 產生空白串列
filter_arr = []

# 利用for迴圈，把陣列每一個元素繞過一圈
for element in arr:
  
  # 如元素的值可被2整除才保留 
  if element % 2 == 0:
  
     filter_arr.append(True) # 利用append函數將True加到串列
  
  else: # 否則移除
    
     filter_arr.append(False) # 利用append函數將False加到串列

# 顯示filter_arr內容
print(filter_arr)

# 利用True/False與位置方式決定是否將arr的元素取出並存放於newarr陣列
newarr = arr[filter_arr]

# 顯示新陣列
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [ ]:
#--------------------------------------------------------------------------------
#%%: 不使用迴圈方式過濾陣列: 大於42元素保留

import numpy as np

arr = np.array([41, 42, 43, 44])

# 過濾條件，注意表達方式
filter_arr = arr > 42

# 直接將過濾條件套用到陣列(此處未使用迴圈，代碼更簡潔)
newarr = arr[filter_arr]

# 顯示filter_arr內容
print(filter_arr)

# 利用True/False與位置方式決定是否將arr的元素取出並存放於newarr陣列
newarr = arr[filter_arr]

# 顯示新陣列
print(newarr)

[False False  True  True]
[43 44]


In [ ]:
#--------------------------------------------------------------------------------
#%%: 不使用迴圈方式過濾陣列: 偶數元素保留

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# 過濾條件，注意表達方式
filter_arr = arr % 2 == 0

# 直接將過濾條件套用到陣列(此處未使用迴圈，代碼更簡潔)
newarr = arr[filter_arr]

# 顯示filter_arr內容
print(filter_arr)

# 利用True/False與位置方式決定是否將arr的元素取出並存放於newarr陣列
newarr = arr[filter_arr]

# 顯示新陣列
print(newarr)

[False  True False  True False  True False]
[2 4 6]


# 隨機值(Random)

In [ ]:
#--------------------------------------------------------------------------------
#%%: 利用pseudo random產生隨機值：代表仍由程式所產生(是可以推算出的)


In [ ]:
#--------------------------------------------------------------------------------
#%%: randint函數: 產生隨機整數

# 在numpy的random方法中
from numpy import random

# 產生0-10間的隨機整數(不含10)
x = random.randint(10)

# 顯示結果
print(x)

8


In [ ]:
#--------------------------------------------------------------------------------
#%%: rand函數：產生0-1之間隨機浮點數(不含1)

from numpy import random

x = random.rand()

# 顯示結果
print(x)

0.46094857119056276


In [ ]:
#--------------------------------------------------------------------------------
#%%: 隨機整數存放於一維陣列

from numpy import random

# 產生隨機0-100之間的5個整數，存放於陣列(由於指定size的關係)
x = random.randint(100, size = (5))

print(x)

[63 80 30 33 91]


In [ ]:
#--------------------------------------------------------------------------------
#%%: 隨機整數存放於二維陣列

from numpy import random

# 3個2維各5個元素的陣列，2維因掛號中有兩個值:3與5
x = random.randint(100, size = (3, 5))

# 顯示結果
print(x)

[[80 32 64 63 63]
 [87 46 50 11  2]
 [69 58 67 50 32]]


In [ ]:
#--------------------------------------------------------------------------------
#%%: 浮點數1維陣列

from numpy import random

# 1維陣列，含5個浮點陣列
x = random.rand(5)

# 顯示結果
print(x)

[0.67284738 0.19134885 0.56315801 0.1685919  0.95400932]


In [ ]:
#--------------------------------------------------------------------------------
#%%: 浮點數2維陣列

from numpy import random

# 2維陣列，3個陣列，各5個元素
x = random.rand(3, 5)

print(x)

[[0.29386299 0.65345393 0.88639416 0.59604602 0.54712931]
 [0.03268145 0.16629758 0.57511086 0.39772757 0.66695705]
 [0.6749569  0.21043788 0.28439431 0.24646855 0.41916594]]


In [ ]:
#--------------------------------------------------------------------------------
#%%: choice函數: 由陣列中的值隨機挑選

from numpy import random

# 從3/5/7/9隨機挑出數字
x = random.choice([3, 5, 7, 9])

# 顯示結果
print(x)

9


In [ ]:
#--------------------------------------------------------------------------------
#%%: choice函數: 由陣列中的值隨機挑選，並產生於陣列

from numpy import random

# 隨機挑出數字，存放於2維3個陣列，個含5個元素
x = random.choice([3, 5, 7, 9], size = (3, 5))

# 顯示結果
print(x)

[[3 5 3 9 5]
 [9 7 3 7 3]
 [5 7 3 3 3]]
